# Site settings
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "G'Dog Mate!"
baseurl = "https://gdogmate.com/"
#theme = "hugo-agency-theme"
paginate = 10
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[params]
  title = "G'Dog Mate!"
  site_author = "Marc Cohen"
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at 
  # fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Your name"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "G'Dog, Mate!"
    # Optional logo as brand stored in img/
    logo = "gdogmate.png"
    mission = "Mission"
    services = "Services & Prices"
    team = "Team"
    portfolio = "Gallery"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
      #url = "http://gohugo.io"
      #name = "External link"
      #weight = 10

  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "G'Dog Mate!"
    subtitle = "Down To Earth<br>Dog Walking Service"
    buttonText = "Tell me more"

  # Mission section
  [params.mission]
    # To change the background image of the mission, replace 'mission.jpg' in
    # the 'static/img' folder.
    enable = true
    title = "Our Mission"
    subtitle = """
Our mission is to provide your dog with exercise, fresh air, and the opportunity to socialize and play, while receiving the attention and care that you yourself would give them. We take groups of no more than 3 dogs for 90 minutes of exercise. Other dog walking services allow as many as 6 dogs per walker, which, we believe, compromises their safety and the level of care they receive. With us, your dog will not spend any walking time being transported in the back of a van and you will always know exactly who is taking care of him/her, because it will be one of us.<br><br>
- Sally & Kimberly
"""

  # Services section
  [params.services]
    enable = true
    title = "Services & Prices"

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-clock-o"
      title = "Schedule"
      description = """
##### **Morning Walk**

9:30-10:00am pick-up<br>
10:00-11:30am walk in park<br>
11:30-12:00pm drop-off

##### **Afternoon Walk**

12:30-1:00pm pick-up<br>
1:00-2:30pm walk in park<br>
2:30-3:00pm drop-off
"""
      url = "#"

    [[params.services.row.list]]
      icon = "fa-gbp"
      title = "Fees"
      description = """
£15 per walk<br />
(£12.50 for weekly bookings)<br />
£10 per addl. dog from same household<br />

##### **First walk free of charge!**
                    """
#<strong>Dogs require microchips and should be up-to-date on vaccinations, flea treatment, and worming.</strong>

      url = "#"

    [[params.services.row.list]]
      icon = "fa-paw"
      title = "Additional Services"
      description = """
<ul style="text-align:left">
<li>Free collection and drop-off (small fee beyond 2-mile radius from N8)</li>
<li>Towel dry and fresh water at drop-off</li>
<li>Regular updates via WhatsApp or Instagram</li>
<li>Home visits available (£10 fee for 30 minutes) for pets who only need a short bathroom break, or require medication or feeding during the day</li>
</ul>
                    """
      url = "#"

  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Our team"
    subtitle = ""
    description = ""

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    [[params.team.members]]
      img = "sally.jpg"
      name = "Sally-Anne"
      #position = "co-founder"
      bio = """
Hello, my name is Sally and I was born in the Peak District and my first best friend was Morgan, my childhood labrador (he took me for a walk!). I’ve many fond memories of long walks with Morgan around the Derbyshire Dales, before emigrating to Australia, where I grew up with cats, dogs, horses, sheep and even a pet Blue Tongue Lizard! I moved back to the UK in 1995 and adopted a lovely little rescue dog from Battersea, whom I named Charlie. I have not found a job more rewarding than spending my time caring for and walking four-legged friends, hence starting up g'dog mate with my friend Kimberly.
      """

    [[params.team.members]]
      img = "kimba.jpg"
      name = "Kimberly"
      #position = "co-founder"
      # For bio markdown and even multiline strings are available.
      bio = """
Greetings!! My name is Kimberly and I’m an American who moved to London 3 years ago, bringing with me my 16-year-old daughter and my 10-year-old mixed breed dog Meiko. Animals are a passion of mine, having previously worked as a veterinarian in the U.S. I’ve also been a vegetarian for more than 30 years, primarily because of my views on animal welfare and my concerns for the ethical treatment of all living things. My friend and business partner, Sally and I are dedicated to providing your pooch with the same loving care that we would give to our own pets. G’day from g'dog mate!
      """

    #[[params.team.members]]
      #img = "yourdog.jpg"
      #name = "Your Dog"
      #position = "client"

  # Portfolio section
  [params.portfolio]
    enable = false
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Gallery"
    subtitle = "Some of our best friends..."
    category = "Category"

    [params.portfolio.modal]
      title = "Gallery"
      subtitle = "Some of our best friends (human and canine)..."
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"

  # Client section
    [params.clients_list]
      enable = false
      # Possibility to center items
      center = true
      # Optional client title specifying the involvement
      title = "Testimonials"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        name = "Simon, owner of Rocky"
        text = "Kimberly has looked after and walked my German Shepherd Collie cross Rocky many times. He’s a very frisky dog that’s isn’t always tolerant of other dogs but Kimberly has the measure of him. He’s always tired and happy by the evening and she’s even taught him to catch a Frisbee. Rocky loves her!"

      [[params.clients]]
        name = "Trissy, owner of Toulouse"
        text = "I've never met anyone who loves dogs as much as Sally Anne. Toulouse our little mini Daxi fell in love with both Sally Anne and Kimberly. From day one I felt so safe leaving our first pup with them both. The WhatsApp pictures and videos is a great way of seeing how much joy our little dog has when she's been cared for. Toulouse can't wait to see you again!"

  # Contact section
  [params.contact]
    enable = true
    headline= "Contact us"
    description = "Give us a call or send us email and we will get back to you as soon as possible!"
    buttonText = "Send message"
    phone = "07508 195629"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "gdogmate@gmail.com"

    # Success and error message overwrite for async contact form
    thanks = "Thank you for contacting us."
    error = "Message could not be sent. Please contact us at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = false
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-twitter"
      link = "#"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
